FROM david6miji/gulp-kor:latest

MAINTAINER David You <david6miji@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

# network util
RUN apt-get install -y net-tools

# gulp-tool 
ENV PATH $PATH:/gulp-tool/

WORKDIR /work

CMD	bash
